#!/usr/bin/env bash
set -e
AONEOPCO=${1:-bulgaria}
ENVIRONMENT=${2:-production}
LANGUAGE=${3:-en}
REACT_APP_LOCAL_DEVELOPMENT=false
REACT_APP_PRODUCTION_BUILD=true


sed -i "s/REACT_APP_SERVICE_SCOPE=.*/REACT_APP_SERVICE_SCOPE=$ENVIRONMENT/" ./.env
sed -i "s/REACT_APP_OPCO=.*/REACT_APP_OPCO=$AONEOPCO/" ./.env
sed -i "s/REACT_APP_PRODUCTION_BUILD=.*/REACT_APP_PRODUCTION_BUILD=$REACT_APP_PRODUCTION_BUILD/" ./.env
sed -i "s/REACT_APP_LOCAL_DEVELOPMENT=.*/REACT_APP_LOCAL_DEVELOPMENT=$REACT_APP_LOCAL_DEVELOPMENT/" ./.env


